### ISSUE TITLE
Feat: evaluate literal values

### ISSUE THREAD

**Issue by jkroepke** [helmfile/vals#100]
Hi,

it would be great, if literal values can be also evaluated:

```
$ printf 'ref+echo://42' | vals eval
42
```

Currently, values need to be wrap into a json/yaml document. It's a bit messy to extract the value inside a shell script.

See https://github.com/jkroepke/helm-secrets/issues/266 for a potential use-case.

**Comment by howieyuen** [comment]
same needs here.

**Comment by mumoshu** [comment]
"Relaxing" `vals eval` not to require a YAML input would be a breaking change for folks relied on it to fail on non-yaml output.
However, another command for getting a single secret value denoted by a vals ref would be feasible.
@jkroepke @howieyuen Would it be still nice if it looked like `vals get`, which can be used like `vals get ref+echo://42'?

**Comment by jkroepke** [comment]
would be fine for me, too!

**Comment by mumoshu** [comment]
@jkroepke Thanks for confirming! #121 is the pull request for that.
