### ISSUE TITLE
Can I move this repository to the Helmfile org?

### ISSUE THREAD

**Issue by mumoshu** [helmfile/vals#106]
Can we move this repository to https://github.com/helmfile so that not only me but also all Helmfile maintainers can co-maintain this project?
We can generally say that the more hands there are the more the project will be maintained well, right? 🤔 
Also, to be clear, note that I'm one of maintainers of the Helmfile project and Helmfile is the biggest public dependent of this project, as far as I know. I believe those two points would justify the move to the Helmfile org if moving it to somewhere is okay in the first place.

**Comment by jkroepke** [comment]
Feel free do to this! :)

No need to ask here... as [helm-secrets](https://github.com/jkroepke/helm-secrets) maintainer which heavily depends on vals, I'm happy to see if the maintenance is guaranteed.

**Comment by mumoshu** [comment]
Thanks for your feedback, everyone! I've moved the repo to the helmfile organization just now.
