### ISSUE TITLE
automated quoting introduced in v0.24.0 causing regressions

### ISSUE THREAD

**Issue by pdeva** [helmfile/vals#142]
this is related to the change introduced by this PR:
https://github.com/helmfile/vals/pull/138

when vals is used with `helm-secrets`, this is now resulting in values being stored with quotes in k8s files where quotes were not expected. This is then causing the relevant apps accessing those values to break. 

An example is when things like pem certificates are put in k8s secrets and referneced via vals in helm chart configs. This change puts quotes around those certificate contents causing the app trying to read the certificate to break.

please atleast provide a flag to disable this automatic quoting.

**Comment by stoned** [comment]
I have submitted jkroepke/helm-secrets#362 to hopefully address this issue.

**Comment by yxxhero** [comment]
see: https://github.com/helmfile/vals/pull/144

**Comment by mdfaizsiddiqui** [comment]
Hey @stoned @yxxhero, Its been a while this fix has been merged but I don't see a new release created for helm-secret, can you help me with that?

Thanks
