### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by mikemowgli** [helmfile/vals#17]
Hi,

Your vals tool looks exactly like what I need, but I can't figure out how to install it.
I tried to "go build" and it works but I can't find the executable. I'm a total beginner to go. Can you provide an installation guide?
Thank you

**Comment by mumoshu** [comment]
@mikemowgli Hey! I'll add binary releases later. Until then, running `go build ./cmd/vals` after git-clone would give you a `vals` executable.

**Comment by jbadeau** [comment]
Hi, any ETA on this. I compiled but a release would be easier

**Comment by TheErk** [comment]
Anything on that front?
Having a ready to use binary release would really be helpful.

**Comment by TheErk** [comment]
My bad there are github binary release now:
https://github.com/variantdev/vals/releases

**Comment by aslafy-z** [comment]
This issue is ready to be closed. Have a look to the Release section, especially the artifacts linked to each releases.
