### ISSUE TITLE
feature request: support Doppler

### ISSUE THREAD

**Issue by carnei-ro** [helmfile/vals#173]
doppler.com is a cool tool and its CLI does a great job; Although it would be nice to have vals (and helmfile) fetching the secrets directly without doppler cli.

**Comment by carnei-ro** [comment]
@yxxhero I created the PR

**Comment by yxxhero** [comment]
@carnei-ro awesome.

**Comment by carnei-ro** [comment]
Thanks for merging it, @yxxhero.
Could you please generate a new tag for this release?
