### ISSUE TITLE
Usage of vals exec -f envvar.yaml with example

### ISSUE THREAD

**Issue by KALAKATASUNEETHA** [helmfile/vals#178]
vals exec command exactly solves my problem by keeping the secrets in a envvar.yaml file to populate env vars and execute them.

envvars.yaml file contains 

`
test-secret: refref+azurekeyvault://********
` 
By running the command vals exec -f envvars.yaml getting the  getting the error msg are "missing args"

**Comment by mumoshu** [comment]
@KALAKATASUNEETHA Hey! `missing args` means you are missing args; it would be run like `vals exec -f yourenvs.yaml -- yourcommand yourarg1 yourarg2`. `vals exec` is used to run your command with the envvars loaded from your yaml file, so it can't be run without any args.
