### ISSUE TITLE
Feature: Add support for service accounts for 1password

### ISSUE THREAD

**Issue by zoispag** [helmfile/vals#181]
Recently 1Password introduced [Service Accounts](https://developer.1password.com/docs/service-accounts/)

> 1Password Service Accounts help automate secrets management in your applications and infrastructure without the need to deploy additional services.

This means we can retrieve secrets from 1password directly, without need to deploy 1Password Connect. The official GitHub action for example has support for both 1Password Connect or 1Password service token: https://developer.1password.com/docs/ci-cd/github-actions/

Any chance the current 1password implementation can be extended to support Service Accounts?

**Comment by yxxhero** [comment]
PR is welcome

**Comment by zoispag** [comment]
Looks like the go SDK does not support service accounts right now.
