### ISSUE TITLE
Feature Request: add support for Kubernetes provider

### ISSUE THREAD

**Issue by lucasfcnunes** [helmfile/vals#185]
Being able to use e.g. `vals get ref+k8s://[[kubeContext/]namespace/]secret#key` seems useful.

---
Request inspired by https://github.com/digitalis-io/vals-operator:
- https://github.com/search?q=repo%3Adigitalis-io%2Fvals-operator+ref%2Bk8s&type=code

**Comment by james-masson** [comment]
Any hints on a method to be able to push Helmfile managed kubeContext natively through to the `k8s.io/client-go` in vals would be useful. ( not through a variable in vals )

**Comment by lucasfcnunes** [comment]
@james-masson

Will it accept optionally `kubeContext` in the path like `vals get ref+k8s://[[kubeContext/]namespace/]secret#key`?

About helmfile templating engine: it could be appended directly in the text of the invocation if there is no explicit `kubeContext` in the `ref+k8s://[[kubeContext/]namespace/]secret#key`.

**Comment by yxxhero** [comment]
@james-masson @lucasfcnunes thanks so much.

**Comment by bersalazar** [comment]
@yxxhero @lucasfcnunes, #186 is the PR @james-masson referred to. It's up now.
