### ISSUE TITLE
Enhancement - Azure Keyvault Support

### ISSUE THREAD

**Issue by cdunford** [helmfile/vals#21]
Would be a great feature to have az keyvault support.

**Comment by mumoshu** [comment]
@cdunford Hey! Yes, it should be a great addition to vals.

Unfortunately, I don't have an Azure account to test it out. Would you mind submitting a PR?

**Comment by cdunford** [comment]
Yeah if I get some time I will give it a go.

**Comment by l-rossetti** [comment]
This is needed also for us. Do you think it's a big task to implement?

**Comment by mumoshu** [comment]
@l-rossetti Not sure how it's big but anyways, I'd gladly review/accept it if you could submit a pull request yourself!

**Comment by l-rossetti** [comment]
I can propose to my company to collaborate but I would need to know:
- will this feature be proposed for helmfile integration as well?
- can someone confirm main development is expected in vals/pkg/providers + string providers?

**Comment by mumoshu** [comment]
@l-rossetti Not sure what you are asking for the first bullet point. I think I've never requested this myself(as I'm mainly an AWS user). So perhaps you should propose it?

Anyways, in reality, helmfile's vals dependency gets updated occasionally. So once the feature is merged to this project, you've eventually get it available within helmfile, too.

For the second point, assuming you're asking about how/where to implement it, I can suggest you to refer to https://github.com/variantdev/vals/pull/20. I think you will need to implement the provider under `pkg/providers/azurekeyvault/*.go` and surface it to the main vals command by updating `./vals.go`.

**Comment by lukasmrtvy** [comment]
@mumoshu 
What about implementing shell datasource ?

Then it should be possible to use something like this:
`ref+sh:["/usr/bin/sh","-c","az keyvault secret show --ids https://cc-production-vault.vault.azure.net/secrets/cc-internal-api-key --version 1 --query value -o tsv"]`
Or even query non sensitive values like:
`ref+sh:["/usr/bin/sh","-c","az identity show -g myRG -n myIdentity --query clientId -o tsv"]`

**Comment by lukasmrtvy** [comment]
For example: https://docs.ansible.com/ansible/latest/plugins/lookup/pipe.html

**Comment by tnaroska** [comment]
Added simple Azure Key Vault secrets support in above PR. Please review.

**Comment by mumoshu** [comment]
Thanks to @tnaroska's awesome work, vals and helmfile already support the Azuer Key Vault!
I'm closing this as resolved.
