### ISSUE TITLE
The release v0.37.4 failed

### ISSUE THREAD

**Issue by suzuki-shunsuke** [helmfile/vals#514]
https://github.com/helmfile/vals/releases/tag/v0.37.4

No asset was released.

<img width="320" alt="image" src="https://github.com/user-attachments/assets/d4bdc2f5-5755-4e0e-a778-584a4be20f25">

GoReleaser failed. https://github.com/helmfile/vals/actions/runs/10747189581/job/29809296379

```
  ⨯ release failed after 6m26s               error=failed to build for darwin_arm64: exit status 1: go: downloading github.com/alessio/shellescape v1.4.1
# runtime/cgo
x86_64-linux-gnu-gcc: error: unrecognized command-line option '-arch'
```

As of v0.37.4, CGO was enabled. I guess this change is related to this issue.

- https://github.com/helmfile/vals/releases/tag/v0.37.4
- https://github.com/helmfile/vals/commit/2fea060e3bb56b166d721b5029ffd562a5a517ff
- https://github.com/helmfile/vals/pull/513

https://github.com/helmfile/vals/blob/5378cfaea5c6fb7db03a0f524b48b0b5e682f1ff/.goreleaser.yml#L6

Seems like the maintainer is aware of this issue.

- https://github.com/helmfile/vals/pull/513#issuecomment-2334981974

**Comment by zhaque44** [comment]
@suzuki-shunsuke good morning, we are actively working to fix this issue. We will notify you once it is fixed, thank you

**Comment by carnei-ro** [comment]
I said here that the Bitwarden Secrets would need CGO enabled and musl-gcc https://github.com/helmfile/vals/issues/427#issuecomment-2334157885
