### ISSUE TITLE
feat: support 1password Secrets Automation

### ISSUE THREAD

**Issue by andrewnazarov** [helmfile/vals#54]
With the recent acquisition of SecretHub and a released feature called Secrets Automation, 1Password became an interesting solution as a secret manager for the whole infrastructure.

https://1password.com/secrets/
https://support.1password.com/secrets-automation/
https://github.com/1Password/connect-sdk-go

It would be great to have it as a possible backend.

**Comment by Nexus2k** [comment]
+1. This would save us a vault deployment.

**Comment by mumoshu** [comment]
1Password rocks! I'd eagerly review any pull requested related to this 👍

**Comment by mmisztal1980** [comment]
I'd be very happy to see this happen. Sadly, the only option, while using ArgoCD, is to use the vault plugin - I'd much rather prefer to use `vals` with helm-secrets.
