### ISSUE TITLE
Vault issue when using pipe (multiline)

### ISSUE THREAD

**Issue by cferrera** [helmfile/vals#57]
### Issue
Not able to fetch Vault secrets when using pipe multiline

> values.yaml.gotmpl (WORKING)
```
certValue: {{ "ref+vault://{PATH}#certificate" }}
```

> values.yaml.gotmpl (NOT WORKING)
```
certValue: | 
{{ "ref+vault://{PATH}#certificate" | indent 2 }}

---

in ./helmfile.yaml: in .helmfiles[0]: in ./helmfile.yaml: failed processing release client-cert: failed to render values files "certs/client-certificate/values.yaml.gotmpl": expand vault://{PATH}#certificate
: no value found for key certificate
```

### Info
> Helm
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

> Helmfile
```
helmfile version v0.139.9
```

> Vault
```
1.3.1
```

Tried so many variations but no success and then I ran out of ideas, if this is a known issue and it should behavior like that maybe I will need to change the chart itself.

Any help is really appreciated.
Thank you.

**Comment by szelenka** [comment]
I'm also running into a similar issue, when trying to use inside tpl
```
data:
    .env.schema: |
      {{- tpl (readFile "config/schema.txt") . | indent 6 }}
```

Where the config/schema.txt contains a line that states:
```text
AUTH_CLIENT_SECRET=ref+vault://secret/PATH#/oauth-client-secret
```

The error returned is:
AUTH_CLIENT_SECRET=ref: no value found for key oauth-client-secret

While we can use `vault kv get --field=oauth-client-secret secret/PATH` and it returns the value just fine

**Comment by gmenuel** [comment]
I've stumbled upon this problem before, and after checking the regex used in vals, I discovered that you can add a "?" at the end of your URI to tell vals that it is the end of the string, otherwise it will read until the end of the string, and can even add newlines.

You should try to use ref+vault://{PATH}#certificate?

**Comment by gmenuel** [comment]
Actually it's not ? but +, my bad. See https://github.com/variantdev/vals/issues/13

**Comment by mumoshu** [comment]
We've finally fixed the original issue of not trealing a new-line character as the expression end, and updated the documentation with a full explanation on our expression syntax, so that everything reported by @cferrera @gmenuel is now covered.
Thanks both for your support!
