### ISSUE TITLE
Implement quiet flag

### ISSUE THREAD

**Issue by jkroepke** [helmfile/vals#60]
Hi,

I'm, currently try to integrate vals into my helm-secret project.

Currently, vals is spammy. There is no way to suppress messages like 

https://github.com/variantdev/vals/blob/0c7d70b4c2f400f16f731ee441655908d45da15a/pkg/providers/sops/sops.go#L51

The debug function would pipe anything to stderr
https://github.com/variantdev/vals/blob/0c7d70b4c2f400f16f731ee441655908d45da15a/pkg/providers/sops/sops.go#L73-L75

I could call vals while stderr is redirect to dev null, but in case of an error, the error messages from vals are gone.

**Comment by mumoshu** [comment]
@jkroepke That sounds like a good addition to vals!

**Comment by jkroepke** [comment]
Alternative:

In general, I would recommend a logging framework that could handle that.

**Comment by mumoshu** [comment]
@jkroepke Thanks for the suggestion! But the Go community doesn't have a single best logging framework so introducing one  would make other logging framework users frustrated. I believe the best way would be to define a simple logger interface in vals and let anyone write an adapter between any logging framework and the vals logger interface.

**Comment by jkroepke** [comment]
I saw this month ago. 

In meanwhile, in java there a tons of [shim implementations](https://logging.apache.org/log4j/2.x/log4j-to-slf4j/index.html) for map method to a different logger.

For know. a simple quiet which hides anything except error would be nice.

My current workaround is to call vals twice

```
    if ! vals "$@" 2>/dev/null; then
        vals "$@" >/dev/null
    fi
```

**Comment by mumoshu** [comment]
I know Java a little and I can say that Go unfortunately doesn't have something like SLF4J for Java 😃

**Comment by jkroepke** [comment]
@mumoshu do you have any idea, if this issue can be addressed? Calling vals twice does not work, if the input comes trough stdin..

**Comment by mumoshu** [comment]
@jkroepke Hey! Just to be extra sure, `vals` not working when run twice against a non-replicated stdin data is another issue than what's mentioned in this issue, right? (I think you'd need to read all the stdin data into another buffer and pass the buffer for each vals run, if you do need to run vals twice for whatever reason

**Comment by jkroepke** [comment]
Correct, I just would like to mention that the workaround from above can not be always used. 

> read all the stdin data into another buffer

Yes, that what I currently do [here](https://github.com/jkroepke/helm-secrets/blob/2b168e670745f79b4dcfe0b23efbfc92d75327b7/scripts/backends/vals.sh#L6-L14), but I'm also looking for an upstream solution like a quiet flag.


Since [logrus](https://github.com/sirupsen/logrus) is in maintenance-mode, [zap](https://github.com/uber-go/zap) seems a good logging solution here.
